quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
%dev.quarkus.datasource.jdbc.url=jdbc:h2:file:./db/h2/orders
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test
quarkus.hibernate-orm.schema-management.strategy=update
%prod.quarkus.datasource.jdbc.url=jdbc:h2:file:./db/h2/orders
%prod.quarkus.hibernate-orm.schema-management.strategy=none
%dropncreate.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
