quarkus.http.port=8080

quarkus.datasource.jdbc.driver=org.h2.Driver
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:file:./db/h2/orders;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test
%prod.quarkus.datasource.jdbc.url=jdbc:h2:file:./db/h2-prod/orders;DB_CLOSE_DELAY=-1

quarkus.hibernate-orm.schema-management.strategy=validate

quarkus.liquibase.migrate-at-start=true
